version: 3

groups:
  chrisB:
    reviewers:
      teams:
      - chris
      
    reviews:
      request: 1
      required: 1
      
  jonA:
    reviewers:
      teams:
      - jon
      
    reviews:
      request: 1
      required: 1
      
    conditions:
    - "'chrisB' in groups.approved"
