version: 3

groups:
  chrisB:
    reviewers:
      teams:
      - chris

  jonA:
    reviewers:
      teams:
      - jon
      users:
      - bdknox

    conditions:
    - "'chrisB' in groups.approved"
